version: '3.8'
services:
  oath:
    image: "xnd-oauth:latest"
    build: .
    ports:
      - "9000:9000"
    environment:
      GITHUB_CLIENT_SECRET: $GITHUB_CLIENT_SECRET
    command: pipenv run gunicorn -b 0.0.0.0:9000 app:app
